[theme]
primaryColor="#FF6B00"
backgroundColor="#1E1E1E"
secondaryBackgroundColor="#2A2A2A"
textColor="#FFFFFF"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
